Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Breadlesscode.SimpleEditorExtend:UiPlugin':
            resource: resource://Breadlesscode.SimpleEditorExtend/Public/UiPlugin/Plugin.js
  Flow:
    mvc:
      routes:
        'Breadlesscode.SimpleEditorExtend': 
          positions: 'start'
